# Use the official node image to build the React app
FROM node:18.13.0


# WORKDIR /install
# COPY package*.json /install
# RUN npm install 
# ENV NODE_PATH=/install/node_modules
# Set the working directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
# COPY package*.json ./
# RUN npm install

# Copy the rest of the client application files
# COPY . .


# this will only run if we don't command in dockerfile.
# CMD [ "npm","start"]
