services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    networks:
      - network_cura
   

networks:
  network_cura:
    external: true

# volumes:
#   node_modules: